# Esempi di Automazioni per AI Assistant

# Esempio 1: Risposta vocale automatica
automation:
  - alias: "AI Assistant - Risposta Vocale"
    description: "Risponde vocalmente alle domande fatte tramite Assist"
    trigger:
      - platform: conversation
        command:
          - "chiedi all'assistente {{ question }}"
          - "domanda all'AI {{ question }}"
          - "ai {{ question }}"
    action:
      - service: ai_assistant.ask_question
        data:
          question: "{{ trigger.slots.question }}"
      - wait_template: "{{ states('sensor.ai_assistant_last_response') != 'Ready' }}"
      - delay: "00:00:01"
      - service: tts.google_say
        data:
          entity_id: media_player.speaker
          message: "{{ states('sensor.ai_assistant_last_response') }}"

# Esempio 2: Notifica su Telegram quando l'AI risponde
automation:
  - alias: "AI Assistant - Notifica Telegram"
    description: "Invia una notifica Telegram quando l'AI risponde"
    trigger:
      - platform: event
        event_type: ai_assistant_response
    action:
      - service: notify.telegram
        data:
          message: >
            🤖 **AI Assistant Risposta**
            
            **Domanda:** {{ trigger.event.data.question }}
            **Risposta:** {{ trigger.event.data.response }}

# Esempio 3: Analisi automatica dello stato della casa
automation:
  - alias: "AI Assistant - Analisi Casa"
    description: "Chiede all'AI di analizzare lo stato della casa"
    trigger:
      - platform: time
        at: "08:00:00"  # Ogni mattina alle 8
    action:
      - service: ai_assistant.ask_question
        data:
          question: >
            Analizza lo stato della casa:
            - Temperatura: {{ states('sensor.temperatura_soggiorno') }}°C
            - Umidità: {{ states('sensor.umidita_soggiorno') }}%
            - Luci accese: {{ states.light | selectattr('state', 'eq', 'on') | list | count }}
            - Dispositivi online: {{ states | selectattr('state', 'ne', 'unavailable') | list | count }}
            
            Fornisci un riepilogo e suggerimenti.

# Esempio 4: Risposta a domande specifiche su dispositivi
automation:
  - alias: "AI Assistant - Info Dispositivi"
    description: "Risponde a domande sui dispositivi"
    trigger:
      - platform: conversation
        command:
          - "stato {{ device }}"
          - "info {{ device }}"
    action:
      - service: ai_assistant.ask_question
        data:
          question: >
            Qual è lo stato di {{ trigger.slots.device }}?
            Il valore attuale è: {{ states(trigger.slots.device) }}

# Esempio 5: Assistente per automazioni
automation:
  - alias: "AI Assistant - Suggerimenti Automazioni"
    description: "Chiede suggerimenti per ottimizzare le automazioni"
    trigger:
      - platform: conversation
        command:
          - "suggerimenti automazioni"
          - "come ottimizzare"
    action:
      - service: ai_assistant.ask_question
        data:
          question: >
            Analizza le seguenti automazioni e suggerisci miglioramenti:
            {% for automation in states.automation %}
            - {{ automation.name }}: {{ automation.state }}
            {% endfor %}

